### ISSUE TITLE
How to get access to global variables

### ISSUE THREAD

**Issue by thetutlage** [vantagejs/vantage-repl#2]
This is how my file looks

``` javascript
var Vorpal = require('vorpal');
var repl = require('vorpal-repl');
var Account = 1;


vorpal
  .delimiter('node~$')
  .use(repl)
  .show();
```

Now inside repl mode when i say `Account` it says `Account is not defined`

**Comment by dthree** [comment]
I need to add a `context` option, [similar to this](https://nodejs.org/api/repl.html). In the meantime, I believe you can hitch things to global, like `GLOBAL.Account`, and this will read when you type `Account`.

Let me throw this `context` thing in as soon as I can.
